### ISSUE TITLE
Query: run time creation of testng.xml and usage of @Factory, @DataProvider

### ISSUE THREAD

**Issue by vikramvi** [canb0/MobileDeviceLab#1]
Thanks for sharing this demo project. I was struggling with parallel setup and your efforts helped a lot.

what do you think of creating testng.xml on run time based on available devices or simulators ?

Also instead of putting data inside testng.xml how about using @Factory, @DataProvider

Please share your thoughts.

Regards,
Vikram

**Comment by canb0** [comment]
Hello Vikram,

I am considering doing testng.xml file during runtime according to device and simulators. That only requires controlling the adb commands and a XML file generation.

Right now we are developing a tool which supports cross browser/device testing. It will also support parallel testing. That's why I stopped playing with that code sample. You can checkout our tool on www.testinium.com . I'll be live in a few months.

**Comment by vikramvi** [comment]
@canb0 thanks for clarification.

Please let me know if you've plans to open source framework ? 
I'm currently developing framework myself, but in case you can open source, would love to contribute back as well.

Regards,
Vikram

**Comment by canb0** [comment]
I don't have any plan to open source it because it requires so much maintenance effort after its release. Right now I am very busy with my job :) But I'll consider open sourcing the project in near future

**Comment by vikramvi** [comment]
Thanks for clarifications @canb0
